### PR TITLE
script ( step 1 )

### PR DESCRIPTION
**Pull request by makswilder**

### CODE REVIEW

**Comment by aaupov** [comment]
Great start! The code is pretty close to our goal, but let's fix some issues:

- [ ] fold commits into one (it's easier to start from scratch),
- [ ] rewrite the commit message to reflect the changes (hint: you're adding perfd),
- [ ] address line-by-line feedback,
- [ ] make sure that the script runs on your machine, producing the expected output.

**Review by makswilder — COMMENTED** [review]
only perf record

**Review by makswilder — COMMENTED** [review]
only perf record

**Comment by makswilder** [comment]
perf record

**Review by makswilder — COMMENTED** [review]
perf record

**Pull request closed without merging**
